# Generated by Django 5.2.16 on 2026-07-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_path',
            field=models.CharField(blank=True, max_length=500, verbose_name='caminho do avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, verbose_name='avatar legado'),
        ),
    ]
