# Generated by Django 5.2.16 on 2026-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_path_alter_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='annuity_valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='anuidade válida até'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='data de nascimento'),
        ),
        migrations.AddField(
            model_name='user',
            name='education_level',
            field=models.CharField(blank=True, max_length=120, verbose_name='nível de escolaridade'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', 'Feminino'), ('male', 'Masculino'), ('non_binary', 'Não binário')], max_length=20, verbose_name='gênero'),
        ),
        migrations.AddField(
            model_name='user',
            name='legacy_imported',
            field=models.BooleanField(db_index=True, default=False, verbose_name='importado da base histórica'),
        ),
        migrations.AddField(
            model_name='user',
            name='member_category',
            field=models.CharField(blank=True, choices=[('full', 'Associado Pleno'), ('junior', 'Associado Júnior'), ('volunteer', 'Voluntário')], max_length=20, verbose_name='categoria do associado'),
        ),
        migrations.AddField(
            model_name='user',
            name='migration_status',
            field=models.CharField(choices=[('native', 'Cadastro nativo'), ('ready', 'Migrado — pronto para primeiro acesso'), ('needs_review', 'Migrado — precisa de revisão')], db_index=True, default='native', max_length=20, verbose_name='situação da migração'),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=True, verbose_name='primeiro acesso concluído'),
        ),
        migrations.AddField(
            model_name='user',
            name='university',
            field=models.CharField(blank=True, max_length=180, verbose_name='universidade/faculdade'),
        ),
    ]
